# This file is for integration testing. 
# These extra wallets keep the relayer wallet separate from the wallet used to send test transactions

networks:
  ethereum:
  # Sepolia
    address: 
    private_key:

  noble:
    address: 
    private_key: